import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "@/components/nav/Nav";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100 max-h-full overflow-auto`}>
        <Suspense fallback={<nav className="p-4 bg-teal-900 flex justify-between items-center sticky top-0"></nav>}>
          <Nav />
        </Suspense>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
